INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('UGEL CARABAYA','SEDE','MACUSANI');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72763 TUPAC AMARU','PRIMARIA','COASA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72780 "Sagrado Corazón de Jesus"','PRIMARIA','SAN GABAN');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72163 "Coasa"','PRIMARIA','COASA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72164 "Sara Chávez"','PRIMARIA','MACUSANI');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72166 "Upina"','PRIMARIA','ITUATA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72167 "Kana"','PRIMARIA','AYAPATA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72168 "Ajoyani"','PRIMARIA','AYAPATA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72169 "Tambillo"','PRIMARIA','ITUATA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72170 "Huanutuyo"','PRIMARIA','MACUSANI');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72171 "Hanac Ayllu"','PRIMARIA','AYAPATA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72172 "Taype"','PRIMARIA','MACUSANI');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72173 "Esquena"','PRIMARIA','COASA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72174 "Ccochahuma"','PRIMARIA','AYAPATA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72175 "Tayac Cucho"','PRIMARIA','ITUATA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72176 "Jorge Chavez"','PRIMARIA','MACUSANI');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72177 "José Antonio Encinas"','PRIMARIA','AYAPATA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72179 "José Carlos Mariategui"','PRIMARIA','OLLACHEA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72180 "Ayapata"','PRIMARIA','AYAPATA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72182 "José María Arguedas Altamirano"','PRIMARIA','CORANI');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72183 "Isivilla"','PRIMARIA','CORANI');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72184 "Glorioso Francisco Bolognesi"','PRIMARIA','SAN GABAN');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72187 "Quelcaya"','PRIMARIA','CORANI');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72188 "Quety"','PRIMARIA','ITUATA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72189 "Quicho"','PRIMARIA','OLLACHEA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72190 "Chacamarca"','PRIMARIA','COASA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72191 "Tantamaco"','PRIMARIA','MACUSANI');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72192 "José Macedo Mendoza"','PRIMARIA','COASA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72194 "Saco"','PRIMARIA','COASA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72196 "Icaco"','PRIMARIA','SAN GABAN');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72197 "Pumachanca"','PRIMARIA','OLLACHEA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72198 "Ccopa"','PRIMARIA','AYAPATA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72199 "Chimboya"','PRIMARIA','CORANI');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72201 "José Antonio Encinas"','PRIMARIA','COASA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72202 "Pago Carabaya"','PRIMARIA','ITUATA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72203 "Cuticarca"','PRIMARIA','COASA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72204 "Ituata"','PRIMARIA','ITUATA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72206 "Tahuana"','PRIMARIA','COASA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72209 "Puente Arica"','PRIMARIA','SAN GABAN');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72210 "Camatani"','PRIMARIA','AYAPATA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72214 "Palca"','PRIMARIA','OLLACHEA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72216 "Kanchi"','PRIMARIA','AYAPATA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72218 "Chacaconiza"','PRIMARIA','CORANI');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72221 "Chia"','PRIMARIA','OLLACHEA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72223 "Asiento"','PRIMARIA','OLLACHEA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72224 "Salimayo"','PRIMARIA','SAN GABAN');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72226 "Huarachani"','PRIMARIA','COASA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72227 "Thiuni"','PRIMARIA','SAN GABAN');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72228 "Ccatacancha"','PRIMARIA','MACUSANI');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72600 "GrandiosoTupac Amaru"','PRIMARIA','MACUSANI');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72603 "Jururusa"','PRIMARIA','ITUATA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72609 Tupac Amaru II','PRIMARIA','CORANI');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72615 "Norberto Odebrecht"','PRIMARIA','SAN GABAN');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72632 "Tambo Punco"','PRIMARIA','ITUATA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72642 "Mallcuapo"','PRIMARIA','ITUATA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72660 "Umachinquini"','PRIMARIA','COASA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72661 "San Francisco de Asís"','PRIMARIA','COASA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72664 "Parusani"','PRIMARIA','OLLACHEA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72666 "Santa Clotilde"','PRIMARIA','SAN GABAN');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72667 "Rosaspata"','PRIMARIA','OLLACHEA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72668 "Bellavista"','PRIMARIA','OLLACHEA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72669 "Nueva Urbanización"','PRIMARIA','AJOYANI');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72670 "Acconsaya"','PRIMARIA','CORANI');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72671 "Queracucho"','PRIMARIA','MACUSANI');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72672 "Jatun Orcco"','PRIMARIA','ITUATA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72673 "Casahuiri"','PRIMARIA','SAN GABAN');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72674 "Puerto Arturo"','PRIMARIA','COASA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72676 "Chullupampa"','PRIMARIA','OLLACHEA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72677 "Munaypata"','PRIMARIA','OLLACHEA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72740 "Loromayo"','PRIMARIA','SAN GABAN');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72741 "Andrés Avelino Cáceres"','PRIMARIA','SAN GABAN');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72742 "El Carmen"','PRIMARIA','SAN GABAN');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72743 "Cuesta Blanca"','PRIMARIA','SAN GABAN');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72745 "Nueva Jerusalen"','PRIMARIA','AYAPATA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72746 "Challhuamayo"','PRIMARIA','SAN GABAN');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72749 " Calasuca"','PRIMARIA','ITUATA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72777 "Tantamayo"','PRIMARIA','SAN GABAN');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72778 "Sangari"','PRIMARIA','SAN GABAN');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 73002 "Glorioso 821"','PRIMARIA','MACUSANI');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72207 "Umachullo"','PRIMARIA','COASA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72217 "Anana"','PRIMARIA','COASA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72213 "Cayandia"','PRIMARIA','COASA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72220 "Punapata"','PRIMARIA','ITUATA');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72665 "Uruwasi"','PRIMARIA','SAN GABAN');
INSERT INTO institucion (inst_name, inst_nivel, distrito) VALUES ('IE. PRIMARIA N° 72211 "Samilia"','PRIMARIA','MACUSANI');
